from node:alpine

workdir /user/src/app

COPY  ./packages ./packages
COPY  ./package.json ./package.json
COPY  ./turbo.json ./turbo.json

COPY  ./apps/web ./apps/web

RUN npm install -g pnpm 
RUN pnpm install --frozen-lockfile

RUN pnpm run generate
RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]


